### ISSUE TITLE
Clarify top-level resource usage

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [cfredric/storage-access-headers#2]
It would be worth it to clarify if a third-party resource in the top-level document can use this to take advantage of the storage-access permission. My gut says that it doesn't make sense to allow that, but I wasn't certain what your intent was after reading this.

**Comment by cfredric** [comment]
I'm not sure if I'm misunderstanding your question, but the main example (https://github.com/cfredric/storage-access-headers#new-flow) is a subresource of the top-level document that requires authentication in order to be retrieved from the cross-site server. The intent is to allow the server to opt in, by responding with the `Activate-Storage-Access: retry` header, so that the fetch is retried with auth credentials this time. (In the case of iframes, this just saves time. The site could alternatively load a placeholder iframe that calls `requestStorageAccess()` and then navigates to the "real" content, with credentials on the fetch.)

I think you might be considering iframes and other kinds of subresources to be different categories? If so, I'd be interested in hearing why.

My thinking was that if the browser ensures that this kind of credentialed subresource fetch is still gated behind a server opt-in (the response header), there shouldn't be a privacy risk to allowing it for non-iframe subresources. (By assumption, the storage-access permission has already been granted, so there's effectively no privacy boundary between the sites if they want to cooperate; just a security boundary, which we uphold by requiring the header opt-in.) I think expanding the ways to opt into storage-access such that non-iframes can participate, makes the permission a lot more useful to sites that serve non-iframe resources which still require credentials.

**Comment by cfredric** [comment]
> Oh, I went in thinking about iframes so I didn't see the main example as another resource.

The point I'm trying to illustrate is that iframes are just one kind of subresource, and the fetches of their content can require authentication too, just like an image/etc.

> Mostly from a performance perspective. Creating a way to get top-level cross-site resources with credentials, but it requires two HTTP requests to do seems like a bad idea.

I agree that the latency required for the two HTTP requests isn't ideal, and I also agree that we ought to think in bigger terms here. To that end, https://github.com/privacycg/storage-access/issues/72 shows that web devs want/expect to be able to embed cross-site, non-iframe subresources (that require auth) in the top-level document. So the question for browsers is, do we believe that is a legitimate use case? I don't see a reason why it shouldn't be, so IMO browsers should make it possible (even if the latency is higher than in other use cases).

> Doing this double-request once per subdocument is less bad.

I think this is a site UX concern, rather than a browser concern. If the web dev *can* design the experience to avoid the extra network request here, then performance is a good incentive for them to do so. But https://github.com/privacycg/storage-access/issues/72 shows that some use cases do not have that option.

> Thinking in big-ideas, only documents can "have storage-access" as of now, so this is a big change beyond just adding headers to improve the ergonomics of getting storage access.

Agreed, I tried to call this out [in the introduction](https://github.com/cfredric/storage-access-headers#enabling-an-authenticated-embed-that-relies-on-non-iframe-subresources-in-the-top-level-page:~:text=Additionally%2C%20the%20use%20of%20HTTP%20headers%20removes%20the%20requirement%20for%20JavaScript%20execution.%20This%20enables%20non%2Diframe%20resources%20to%20take%20full%20advantage%20of%20existing%20storage%2Daccess%20permission%20grants.) and [in the key scenarios section](https://github.com/cfredric/storage-access-headers#enabling-an-authenticated-embed-that-relies-on-non-iframe-subresources-in-the-top-level-page).

**Comment by cfredric** [comment]
FWIW, CORS preflight requests are a precedent where the browser makes an extra network request before doing something sensitive, to make sure the server is ok with it first.

In the case of CORS, the "sensitive thing" is to make a non-idempotent cross-origin request.

Here, the "sensitive thing" is to make a credentialed cross-site request. (That's sensitive due to CSRF concerns, of course.)

**Comment by bvandersloot-mozilla** [comment]
Fair enough. I think I buy that use of top-level resources is probably reasonable. However could we restrict it some...

I'm going to move the CORS discussion to a new issue...

**Comment by cfredric** [comment]
Closing this issue, continuing discussion in the other one.
